<?php


function ajax_field_update_menu(){
  
  $items = array();

  $items['ajax_field_update/%/%/%'] = array(
    'title' => 'Ajax field update',
    'page callback' => 'ajax_field_update_update_field',
    'page arguments' => array(1,2,3),
    'access arguments' => array('access content'),
    'description' => '',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;

}

function ajax_field_update_update_field($entity_type, $entity_id, $field_name){

  $entity = entity_load_single($entity_type,$entity_id);

  if(entity_access('update',$entity_type, $entity)){

    if(isset($_POST['value'])){

      // @todo: massive todo here, assumes LANGUAGE_NONE, cardinality 1, "value". basically just for single value text fields atm
      // - actually I guess I can just pass all that in too:
      $language = isset($_POST['lang']) ? $_POST['lang'] : LANGUAGE_NONE;
      $delta = isset($_POST['delta']) ? $_POST['delta'] : 0;
      $target = isset($_POST['target']) ? $_POST['target'] : 'value';
      // 'target' could be eg 'value', 'tid', etc
      $entity->{$field_name}[$language][$delta][$target] = $_POST['value'];
      
      $result = entity_save($entity_type,$entity);

      if($result !== false){
        $result = 'Updated ' . $field_name;
        $success = 1;
      }else{
        $result = "Couldn't save entity";

        $success = 0;
      }

    }else{

      $result = 'no value supplied!';
      $success = 0;

    }

  }else{

    $result = 'access denied!';
    $success = 0;
  
  }

  drupal_json_output(array('result' => $result, 'success' => $success));

}